# Configuration for dask cluster on NCI (Gadi)

PBSCluster:
  processes: 1
  walltime: '01:00:00'
  cores: 24
  memory: 48GB
  job_extra:
    - '-l ncpus=24'
    - '-l mem=48GB'
    - '-P ux06'
    - '-l jobfs=100GB'
    - '-l storage=gdata/xv83+gdata/v14+scratch/v14'
  local_directory: $PBS_JOBFS
  header_skip:
    - select

