name: unseen-test
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - cmdline_provenance
  - dask-core
  - dask-jobqueue
  - geopandas
  - gitpython
  - lmoments3
  - netcdf4
  - numpy
  - pip
  - pytest
  - python
  - regionmask
  - scipy>=1.10.0
  - seaborn
  - xarray
  - xclim>=0.39.0
  - xesmf
  - xskillscore
  - zarr
  - pip:
    - codecov
    - pytest-cov
    - xstatstests
