name: unseen-test
channels:
  - conda-forge
dependencies:
  - python
  - geopandas
  - regionmask
  - xarray
  - dask-core
  - numpy
  - pytest
  - cftime
  - gitpython
  - cmdline_provenance
  - xclim
  - xskillscore
  - seaborn
  - zarr
  - netcdf4
  - dask-jobqueue
  - pip
  - pip:
    - codecov
    - pytest-cov
    - xstatstests
