name: unseen-test
channels:
  - conda-forge
dependencies:
  - python=3.9
  - geopandas
  - regionmask
  - xarray
  - dask-core
  - numpy
  - pytest
  - cftime
  - gitpython
  - cmdline_provenance
  - xclim
  - dask-jobqueue
  - pip
  - pip:
    - codecov
    - pytest-cov
