name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment-${{ matrix.python-version }}.yml
          activate-environment: unseen-test
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        run: python -m pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest unseen

      - name: Code coverage
        uses: codecov/codecov-action@v1
